name: Deploy Demo

on:
  push:
    branches:
      - demo

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup Middleware Config
        run: |
          echo "${{ secrets.MIDDLEWARE_CONFIG }}" | base64 -d > workers/kv-management-middleware/wrangler.json

      - name: Install Dependencies
        working-directory: ./workers/kv-management-middleware
        run: npm install && npm install -g wrangler

      - name: Deploy Middleware
        working-directory: ./workers/kv-management-middleware
        run: |
          wrangler deploy > /dev/null 2>&1
          echo "${{ secrets.WORKER_KV_SECRET }}" | wrangler secret put WORKER_KV_SECRET
          echo "${{ secrets.TURNSTILE_SECRET_KEY }}" | wrangler secret put TURNSTILE_SECRET_KEY
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Install Dependencies
        working-directory: ./workers/kv-management-ui
        run: npm install && npm install -g wrangler

      - name: Build and Deploy UI
        working-directory: ./workers/kv-management-ui
        run: |
          echo "VITE_APP_WORKER_KV_SECRET=${{ secrets.WORKER_KV_SECRET }}" > .env
          echo "VITE_APP_WORKER_URL=https://kv-management-middleware-demo.someworkers.workers.dev" >> .env
          echo "VITE_APP_CUSTOM_HEADER=X-Custom-Auth" >> .env
          echo "VITE_APP_TURNSTILE_SITE_KEY=${{ secrets.TURNSTILE_SITE_KEY }}" >> .env
          echo "VITE_MIDDLEWARE_USE_ZERO_TRUST=false" >> .env
          npm run build
          wrangler pages deploy ./dist --branch=demo
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
