name: Deploy Demo

on:
  push:
    branches:
      - demo

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup Middleware Config
        run: |
          echo "${{ secrets.MIDDLEWARE_CONFIG }}" | base64 -d > workers/kv-management-middleware/wrangler.json

      - name: Install Dependencies
        working-directory: ./workers/kv-management-middleware
        run: npm install && npm install -g wrangler

      - name: Deploy Middleware
        working-directory: ./workers/kv-management-middleware
        run: |
          wrangler deploy


      # - name: Deploy Middleware
      #   uses: cloudflare/wrangler-action@3.0.0
      #   with:
      #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #     accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      #     workingDirectory: ./workers/kv-management-middleware
      #     secrets: |
      #       WORKER_KV_SECRET
      #       TURNSTILE_SECRET_KEY
      #   env:
      #     WORKER_KV_SECRET: ${{ secrets.WORKER_KV_SECRET }}
      #     TURNSTILE_SECRET_KEY: ${{ secrets.TURNSTILE_SECRET_KEY }}

      - name: Install Dependencies
        working-directory: ./workers/kv-management-ui
        run: npm install
      - name: Build Project
        run: npm run build
        working-directory: ./workers/kv-management-ui
      - name: Deploy UI
        uses: cloudflare/wrangler-action@3.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ./workers/kv-management-ui
          command: "pages deploy --directory=dist --project-name=kv-management-ui-demo"
